// import './clone-arr'
// import './balanced-bracket'
// import './palindrome'
// import './flatten-distinct'
// import './rot13'
// import './remove-dups'
// import './phone-num-format'
// import './sum-two-arr'
// import './find-dups'
// import './index-indicator-sum'
// import './longestCommonStr'
import './truncateStr'